#  Matrix-Vector Operations with numpy.dot 

In [2]:
import numpy as np

In [3]:
a=np.random.randn(3)
print(a.shape,a)

(3,) [ 0.91384355  0.28619198 -0.454829  ]


In [4]:
M=np.random.randn(3,4)
print(M.shape,M)

(3, 4) [[-0.58406878 -0.29245727  0.82857086 -2.57805558]
 [ 0.76043143  0.49877376 -1.70995547 -0.39897025]
 [ 1.38594246 -2.59946059  1.88923253  0.72401486]]


We have a one-dimensional vector (3,) a, and an array (3,4) M.  dot(M,a) should result in an error because the dimensions are mis-matched for matrix times column-vector

In [5]:
Ma=np.dot(M,a)

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

Row multiplication a M should work, returning a 4-element row-vector

In [6]:
aM = np.dot(a,M)
print(aM.shape)
print(aM)

(4,)
[-0.94648493  1.05779492 -0.59146915 -2.79942449]


The arrays with shape (n,) get treated by np.dot as row vectors or column vectors depending on how they are positioned relative to the matrix.

Now we'll explicity create row and column vectors and see if np.dot respects the rules

In [8]:
ac = np.random.randn(3,1)
print(ac.shape)
print(ac)

(3, 1)
[[-1.02141036]
 [ 0.73961783]
 [-0.07097736]]


In [9]:
acM = np.dot(ac,M)

ValueError: shapes (3,1) and (3,4) not aligned: 1 (dim 1) != 3 (dim 0)

Which is a good failure, this should work.

In [10]:
acM=np.dot(ac.T,M)
print(acM.shape)
print(acM)

(1, 4)
[[ 1.06063201  0.8521237  -2.24511715  2.28677851]]


The new infix operator should do the same.

In [11]:
check_acM = ac.T @ M
print(check_acM.shape)
print(check_acM)

(1, 4)
[[ 1.06063201  0.8521237  -2.24511715  2.28677851]]


dot(M,ac) should fail because of the dimension mis-match

In [12]:
np.dot(M,ac)

ValueError: shapes (3,4) and (3,1) not aligned: 4 (dim 1) != 3 (dim 0)

And we should get a proper matrix-column vector multiply out of this

In [13]:
np.dot(M.T,ac)

array([[ 1.06063201],
       [ 0.8521237 ],
       [-2.24511715],
       [ 2.28677851]])

In [14]:
M.T @ ac

array([[ 1.06063201],
       [ 0.8521237 ],
       [-2.24511715],
       [ 2.28677851]])